apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkding-deploy
  name: linkding-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkding-deploy
  template:
    metadata:
      labels:
        app: linkding-deploy
    spec:
      containers:
      - image: sissbruecker/linkding:1.38.0
        name: linkding
        ports:
        - containerPort: 9090
