apiVersion: v1
kind: Service
metadata:
  labels:
    app: linkding-deploy
  name: linkding-svc
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: linkding-deploy
  type: LoadBalancer
