apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: deploy
  name: deploy
spec:
  containers:
  - args:
    - test
    - replicas=3
    image: nginx
    name: deploy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
